### ISSUE TITLE
[podstawy] wybór kolorów

### ISSUE THREAD

**Issue by kruzyk** [szywac/szywac.github.io#4]
- [x] kolory poszczególnych sekcji
- [x] kolory dla nagłówków
- [x] kolory dla tekstu
- [x] kolory dla linków

**Comment by kruzyk** [comment]
Tak jak rozmawialiśmy, skoro chcesz żeby sekcje różniły się stopniowo odcieniem koloru, wybierz odcień dla każdej sekcji i zastanów się, jakie kolory ustawić dla elementów w każdej sekcji.
Chyba, że ustawiamy taki sam kolor dla całego tekstu bo kolory sekcji mało się od siebie różnią.

**sekcja 1**
- tło:
- nagłówek:
- treść:
**sekcja 2**
- tło:
- nagłówek:
- treść:
**sekcja 3**
- tło:
- nagłówek:
- treść:
**sekcja 4**
- tło:
- nagłówek:
- treść:
**sekcja 5**
- tło:
- nagłówek:
- treść:

**Comment by szywac** [comment]
sekcja 1
tło: #73B600
nagłówek: #A9EE34
treść: #497300

sekcja 2
tło: #009813
nagłówek: #2CCA3F
treść: #30843A

sekcja 3
tło: #5CB100
nagłówek: #3A7000
treść: #91E833

sekcja 4
tło: #37AA00
nagłówek: #1B5300
treść: #47DC00

sekcja 5
tło: #4DC300
nagłówek: #215500
treść: #63FB00
